module.exports = {
	CAPTCHA_SITE_KEY:'YOUR_SITE_KEY_HERE',
	CAPTCHA_SITE_SECRET:'YOUR_CAPTCHA_SECRET',
	MAIL_USER:'YOUR_USERNAME_HERE',
	MAIL_PASS:'YOUR_PASSWORD_HERE',
	MAIL_TO:'MAIL_TO_ADDRESS',
	MAIL_FROM:'MAIL_FROM_ADDRESS'
}